# .github/workflows/ci.yml

name: CI/CD Payment System

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    # اجازه نوشتن در مخزن برای Commit خودکار
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest black flake8

      - name: Auto-format code with Black
        run: |
          black .

      - name: Check if any changes after Black
        id: git_diff
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit formatting changes
        if: steps.git_diff.outputs.changes == 'true' && github.event_name == 'push'
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          message: 'Apply Black auto-formatting'
          # اگر شاخه اصلی شما چیزی غیر از main است، آن را عوض کنید
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Flake8 linting
        run: |
          flake8 .

      - name: Run tests with pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Build Docker image for Payment System
        run: |
          docker build . -t payment-system

      - name: Run Docker Compose for integration testing
        run: |
          docker-compose up --build -d
          # در صورت نیاز، کمی تاخیر برای راه‌اندازی سرویس‌ها
          sleep 10
          docker-compose ps

      - name: Tear down Docker Compose services
        if: always()
        run: docker-compose down
